--
-- PostgreSQL database dump
--

\restrict gYPoJvAMGUkWfZr4oZpLBVmmbDK9dc9fS2ue8AfLrQiHC3z5DHMFdpCfQhxnrg2

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: site; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.site (
    id integer NOT NULL,
    access character varying(255),
    depth character varying(255),
    coef_max integer,
    name character varying(255),
    nationality character varying(255),
    port character varying(255),
    sector character varying(255),
    size character varying(255),
    sunk_on character varying(255),
    theoretical_current character varying(255),
    type character varying(255)
);


ALTER TABLE public.site OWNER TO diving_db_user;

--
-- Name: site_coordinate; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.site_coordinate (
    id integer NOT NULL,
    description character varying(255),
    is_confirmed boolean,
    lat_deg integer,
    lat_dir character varying(255),
    lat_min double precision,
    lon_deg integer,
    lon_dir character varying(255),
    lon_min double precision,
    site_id integer
);


ALTER TABLE public.site_coordinate OWNER TO diving_db_user;

--
-- Name: site_coordinate_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.site_coordinate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_coordinate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_diving_experience_moment; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.site_diving_experience_moment (
    experimentation_id integer NOT NULL,
    moment_id integer NOT NULL
);


ALTER TABLE public.site_diving_experience_moment OWNER TO diving_db_user;

--
-- Name: site_diving_experimentation; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.site_diving_experimentation (
    id integer NOT NULL,
    coefficient integer,
    comment character varying(255),
    created_at timestamp(6) without time zone,
    current_score integer,
    dive_date date,
    observed_depth double precision,
    site_id integer
);


ALTER TABLE public.site_diving_experimentation OWNER TO diving_db_user;

--
-- Name: site_diving_experimentation_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.site_diving_experimentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_diving_experimentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_theoretical_tide; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.site_theoretical_tide (
    vitesse character varying(255),
    moment_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.site_theoretical_tide OWNER TO diving_db_user;

--
-- Name: t_activity; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_activity (
    activityid integer NOT NULL,
    comment character varying(255),
    companyid integer,
    directorid integer,
    diving_place character varying(255),
    ending_date date,
    ending_time time(6) without time zone,
    name character varying(255),
    participant_number integer,
    place character varying(255),
    sectionid integer,
    spectator_number integer,
    starting_date date,
    starting_time time(6) without time zone,
    statusid integer,
    tide_down time(6) without time zone,
    tideup time(6) without time zone,
    tide_value integer,
    "timestamp" timestamp(6) without time zone,
    userid integer
);


ALTER TABLE public.t_activity OWNER TO diving_db_user;

--
-- Name: t_activity_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

CREATE SEQUENCE public.t_activity_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.t_activity_seq OWNER TO diving_db_user;

--
-- Name: t_certifications; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_certifications (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by integer,
    description character varying(255),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by integer
);


ALTER TABLE public.t_certifications OWNER TO diving_db_user;

--
-- Name: t_certifications_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.t_certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_certifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_company; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_company (
    id integer NOT NULL,
    name character varying(255),
    "timestamp" timestamp(6) without time zone,
    userid integer NOT NULL
);


ALTER TABLE public.t_company OWNER TO diving_db_user;

--
-- Name: t_diver; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_diver (
    diverid integer NOT NULL,
    address character varying(255) NOT NULL,
    birthdate date NOT NULL,
    city character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by integer,
    email character varying(255),
    firstname character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    medical_certificate_date date NOT NULL,
    parental_authorization boolean,
    phone_number character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by integer,
    zip character varying(255) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.t_diver OWNER TO diving_db_user;

--
-- Name: t_diver_activity; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_diver_activity (
    diverid integer NOT NULL,
    activityid integer NOT NULL
);


ALTER TABLE public.t_diver_activity OWNER TO diving_db_user;

--
-- Name: t_diver_certifications; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_diver_certifications (
    diver_id integer NOT NULL,
    certification_id integer NOT NULL
);


ALTER TABLE public.t_diver_certifications OWNER TO diving_db_user;

--
-- Name: t_diver_diverid_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.t_diver ALTER COLUMN diverid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_diver_diverid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_diver_qualification; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_diver_qualification (
    diverid integer NOT NULL,
    qualificationid integer NOT NULL
);


ALTER TABLE public.t_diver_qualification OWNER TO diving_db_user;

--
-- Name: t_diver_qualification_studies; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_diver_qualification_studies (
    diverid integer NOT NULL,
    qualification_studiesid integer NOT NULL
);


ALTER TABLE public.t_diver_qualification_studies OWNER TO diving_db_user;

--
-- Name: t_documents; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_documents (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by integer,
    expiry_date timestamp(6) without time zone,
    file_path character varying(255) NOT NULL,
    issue_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    diver_id integer NOT NULL
);


ALTER TABLE public.t_documents OWNER TO diving_db_user;

--
-- Name: t_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.t_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_qualification; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_qualification (
    qualificationid integer NOT NULL,
    description character varying(255),
    companyid integer,
    director_nitrox boolean NOT NULL,
    director_sea boolean NOT NULL,
    director_swiming_pool boolean NOT NULL,
    max_sea_diver_depth integer,
    max_sea_supervisor_depth integer,
    max_sea_teacher_depth integer,
    max_swimming_depth integer,
    name character varying(255),
    nitrox_maxppn2 integer,
    supervisor_sea_authorization boolean NOT NULL,
    teacher_sea_authorization boolean NOT NULL,
    "timestamp" timestamp(6) without time zone,
    userid integer
);


ALTER TABLE public.t_qualification OWNER TO diving_db_user;

--
-- Name: t_qualification_studies; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_qualification_studies (
    qualification_studiesid integer NOT NULL,
    description character varying(255),
    companyid integer,
    director_nitrox integer,
    director_sea boolean NOT NULL,
    director_swiming_pool boolean NOT NULL,
    max_sea_diver_depth integer,
    max_sea_supervisor_depth integer,
    max_sea_teacher_depth integer,
    max_swimming_depth integer,
    name character varying(255),
    nitrox_maxppn2 integer,
    supervisor_sea_authorization boolean NOT NULL,
    teacher_sea_authorization boolean NOT NULL,
    "timestamp" timestamp(6) without time zone,
    userid integer
);


ALTER TABLE public.t_qualification_studies OWNER TO diving_db_user;

--
-- Name: t_roles; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_roles (
    roleid integer NOT NULL,
    companyid integer,
    role_name character varying(255),
    "timestamp" timestamp(6) without time zone,
    userid integer
);


ALTER TABLE public.t_roles OWNER TO diving_db_user;

--
-- Name: t_section; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_section (
    id integer NOT NULL,
    companyid integer,
    name character varying(255),
    "timestamp" timestamp(6) without time zone,
    userid integer
);


ALTER TABLE public.t_section OWNER TO diving_db_user;

--
-- Name: t_spectator_activity; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_spectator_activity (
    diverid integer NOT NULL,
    activityid integer NOT NULL
);


ALTER TABLE public.t_spectator_activity OWNER TO diving_db_user;

--
-- Name: t_url_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

CREATE SEQUENCE public.t_url_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.t_url_seq OWNER TO diving_db_user;

--
-- Name: t_user_h; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_user_h (
    id integer NOT NULL,
    address character varying(255),
    archived_at timestamp(6) without time zone NOT NULL,
    archived_by integer,
    birth_date character varying(255),
    city character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone_number character varying(255),
    user_id integer,
    user_name character varying(255),
    useruuid character varying(255),
    zip_code character varying(255)
);


ALTER TABLE public.t_user_h OWNER TO diving_db_user;

--
-- Name: t_user_h_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.t_user_h ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_user_h_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_users; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.t_users (
    id integer NOT NULL,
    address character varying(255),
    birth_date character varying(255),
    city character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    created_by integer,
    first_name character varying(255),
    last_name character varying(255),
    phone_number character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by integer,
    user_name character varying(255),
    useruuid character varying(255) NOT NULL,
    zip_code character varying(255)
);


ALTER TABLE public.t_users OWNER TO diving_db_user;

--
-- Name: t_users_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.t_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tide_moment; Type: TABLE; Schema: public; Owner: diving_db_user
--

CREATE TABLE public.tide_moment (
    id integer NOT NULL,
    label character varying(255) NOT NULL
);


ALTER TABLE public.tide_moment OWNER TO diving_db_user;

--
-- Name: tide_moment_id_seq; Type: SEQUENCE; Schema: public; Owner: diving_db_user
--

ALTER TABLE public.tide_moment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tide_moment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: site; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.site (id, access, depth, coef_max, name, nationality, port, sector, size, sunk_on, theoretical_current, type) FROM stdin;
\.


--
-- Data for Name: site_coordinate; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.site_coordinate (id, description, is_confirmed, lat_deg, lat_dir, lat_min, lon_deg, lon_dir, lon_min, site_id) FROM stdin;
\.


--
-- Data for Name: site_diving_experience_moment; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.site_diving_experience_moment (experimentation_id, moment_id) FROM stdin;
\.


--
-- Data for Name: site_diving_experimentation; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.site_diving_experimentation (id, coefficient, comment, created_at, current_score, dive_date, observed_depth, site_id) FROM stdin;
\.


--
-- Data for Name: site_theoretical_tide; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.site_theoretical_tide (vitesse, moment_id, site_id) FROM stdin;
\.


--
-- Data for Name: t_activity; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_activity (activityid, comment, companyid, directorid, diving_place, ending_date, ending_time, name, participant_number, place, sectionid, spectator_number, starting_date, starting_time, statusid, tide_down, tideup, tide_value, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_certifications; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_certifications (id, created_at, created_by, description, name, updated_at, updated_by) FROM stdin;
\.


--
-- Data for Name: t_company; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_company (id, name, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_diver; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_diver (diverid, address, birthdate, city, created_at, created_by, email, firstname, last_name, medical_certificate_date, parental_authorization, phone_number, updated_at, updated_by, zip, user_id) FROM stdin;
\.


--
-- Data for Name: t_diver_activity; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_diver_activity (diverid, activityid) FROM stdin;
\.


--
-- Data for Name: t_diver_certifications; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_diver_certifications (diver_id, certification_id) FROM stdin;
\.


--
-- Data for Name: t_diver_qualification; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_diver_qualification (diverid, qualificationid) FROM stdin;
\.


--
-- Data for Name: t_diver_qualification_studies; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_diver_qualification_studies (diverid, qualification_studiesid) FROM stdin;
\.


--
-- Data for Name: t_documents; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_documents (id, created_at, created_by, expiry_date, file_path, issue_date, type, updated_at, updated_by, diver_id) FROM stdin;
\.


--
-- Data for Name: t_qualification; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_qualification (qualificationid, description, companyid, director_nitrox, director_sea, director_swiming_pool, max_sea_diver_depth, max_sea_supervisor_depth, max_sea_teacher_depth, max_swimming_depth, name, nitrox_maxppn2, supervisor_sea_authorization, teacher_sea_authorization, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_qualification_studies; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_qualification_studies (qualification_studiesid, description, companyid, director_nitrox, director_sea, director_swiming_pool, max_sea_diver_depth, max_sea_supervisor_depth, max_sea_teacher_depth, max_swimming_depth, name, nitrox_maxppn2, supervisor_sea_authorization, teacher_sea_authorization, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_roles; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_roles (roleid, companyid, role_name, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_section; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_section (id, companyid, name, "timestamp", userid) FROM stdin;
\.


--
-- Data for Name: t_spectator_activity; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_spectator_activity (diverid, activityid) FROM stdin;
\.


--
-- Data for Name: t_user_h; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_user_h (id, address, archived_at, archived_by, birth_date, city, first_name, last_name, phone_number, user_id, user_name, useruuid, zip_code) FROM stdin;
\.


--
-- Data for Name: t_users; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.t_users (id, address, birth_date, city, created_at, created_by, first_name, last_name, phone_number, updated_at, updated_by, user_name, useruuid, zip_code) FROM stdin;
\.


--
-- Data for Name: tide_moment; Type: TABLE DATA; Schema: public; Owner: diving_db_user
--

COPY public.tide_moment (id, label) FROM stdin;
\.


--
-- Name: site_coordinate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.site_coordinate_id_seq', 1, false);


--
-- Name: site_diving_experimentation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.site_diving_experimentation_id_seq', 1, false);


--
-- Name: site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.site_id_seq', 1, false);


--
-- Name: t_activity_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_activity_seq', 1, false);


--
-- Name: t_certifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_certifications_id_seq', 1, false);


--
-- Name: t_diver_diverid_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_diver_diverid_seq', 1, false);


--
-- Name: t_documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_documents_id_seq', 1, false);


--
-- Name: t_url_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_url_seq', 1, false);


--
-- Name: t_user_h_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_user_h_id_seq', 1, false);


--
-- Name: t_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.t_users_id_seq', 1, false);


--
-- Name: tide_moment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: diving_db_user
--

SELECT pg_catalog.setval('public.tide_moment_id_seq', 1, false);


--
-- Name: site_coordinate site_coordinate_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_coordinate
    ADD CONSTRAINT site_coordinate_pkey PRIMARY KEY (id);


--
-- Name: site_diving_experimentation site_diving_experimentation_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_diving_experimentation
    ADD CONSTRAINT site_diving_experimentation_pkey PRIMARY KEY (id);


--
-- Name: site site_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site
    ADD CONSTRAINT site_pkey PRIMARY KEY (id);


--
-- Name: site_theoretical_tide site_theoretical_tide_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_theoretical_tide
    ADD CONSTRAINT site_theoretical_tide_pkey PRIMARY KEY (moment_id, site_id);


--
-- Name: t_activity t_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_activity
    ADD CONSTRAINT t_activity_pkey PRIMARY KEY (activityid);


--
-- Name: t_certifications t_certifications_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_certifications
    ADD CONSTRAINT t_certifications_pkey PRIMARY KEY (id);


--
-- Name: t_company t_company_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_company
    ADD CONSTRAINT t_company_pkey PRIMARY KEY (id);


--
-- Name: t_diver_activity t_diver_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_activity
    ADD CONSTRAINT t_diver_activity_pkey PRIMARY KEY (diverid, activityid);


--
-- Name: t_diver t_diver_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver
    ADD CONSTRAINT t_diver_pkey PRIMARY KEY (diverid);


--
-- Name: t_diver_qualification t_diver_qualification_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_qualification
    ADD CONSTRAINT t_diver_qualification_pkey PRIMARY KEY (diverid, qualificationid);


--
-- Name: t_diver_qualification_studies t_diver_qualification_studies_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_qualification_studies
    ADD CONSTRAINT t_diver_qualification_studies_pkey PRIMARY KEY (diverid, qualification_studiesid);


--
-- Name: t_documents t_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_documents
    ADD CONSTRAINT t_documents_pkey PRIMARY KEY (id);


--
-- Name: t_qualification t_qualification_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_qualification
    ADD CONSTRAINT t_qualification_pkey PRIMARY KEY (qualificationid);


--
-- Name: t_qualification_studies t_qualification_studies_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_qualification_studies
    ADD CONSTRAINT t_qualification_studies_pkey PRIMARY KEY (qualification_studiesid);


--
-- Name: t_roles t_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_roles
    ADD CONSTRAINT t_roles_pkey PRIMARY KEY (roleid);


--
-- Name: t_section t_section_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_section
    ADD CONSTRAINT t_section_pkey PRIMARY KEY (id);


--
-- Name: t_spectator_activity t_spectator_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_spectator_activity
    ADD CONSTRAINT t_spectator_activity_pkey PRIMARY KEY (diverid, activityid);


--
-- Name: t_user_h t_user_h_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_user_h
    ADD CONSTRAINT t_user_h_pkey PRIMARY KEY (id);


--
-- Name: t_users t_users_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_users
    ADD CONSTRAINT t_users_pkey PRIMARY KEY (id);


--
-- Name: tide_moment tide_moment_pkey; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.tide_moment
    ADD CONSTRAINT tide_moment_pkey PRIMARY KEY (id);


--
-- Name: tide_moment ukeie18ofagfqs3r0wl6viii1dx; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.tide_moment
    ADD CONSTRAINT ukeie18ofagfqs3r0wl6viii1dx UNIQUE (label);


--
-- Name: t_users ukpl6abmrrpg6q0bvdr9dg0lnhs; Type: CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_users
    ADD CONSTRAINT ukpl6abmrrpg6q0bvdr9dg0lnhs UNIQUE (useruuid);


--
-- Name: site_theoretical_tide fk2f3c788yfnfe2ruejau25alf8; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_theoretical_tide
    ADD CONSTRAINT fk2f3c788yfnfe2ruejau25alf8 FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- Name: site_coordinate fk4rl1cyrdkdh8sfondhylxreac; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_coordinate
    ADD CONSTRAINT fk4rl1cyrdkdh8sfondhylxreac FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- Name: t_diver_certifications fk7yt1iopw6cbkki574ib72w1jb; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_certifications
    ADD CONSTRAINT fk7yt1iopw6cbkki574ib72w1jb FOREIGN KEY (diver_id) REFERENCES public.t_diver(diverid);


--
-- Name: t_diver_qualification_studies fk9hea0iwe533l23c7aottjuq63; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_qualification_studies
    ADD CONSTRAINT fk9hea0iwe533l23c7aottjuq63 FOREIGN KEY (qualification_studiesid) REFERENCES public.t_qualification_studies(qualification_studiesid);


--
-- Name: site_theoretical_tide fk9ns82xn10vratn2kxp8g2aou4; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_theoretical_tide
    ADD CONSTRAINT fk9ns82xn10vratn2kxp8g2aou4 FOREIGN KEY (moment_id) REFERENCES public.tide_moment(id);


--
-- Name: t_diver_certifications fka8wdnegexdg5iqd2tnf4xd2da; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_certifications
    ADD CONSTRAINT fka8wdnegexdg5iqd2tnf4xd2da FOREIGN KEY (certification_id) REFERENCES public.t_certifications(id);


--
-- Name: site_diving_experience_moment fkb8nlev4tfpiiv8weoiybgy026; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_diving_experience_moment
    ADD CONSTRAINT fkb8nlev4tfpiiv8weoiybgy026 FOREIGN KEY (experimentation_id) REFERENCES public.site_diving_experimentation(id);


--
-- Name: t_documents fkd5iy7im85trakfphd3i86cgtn; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_documents
    ADD CONSTRAINT fkd5iy7im85trakfphd3i86cgtn FOREIGN KEY (diver_id) REFERENCES public.t_diver(diverid);


--
-- Name: t_diver fkkm718p6ftmtmr8balobaj8n7d; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver
    ADD CONSTRAINT fkkm718p6ftmtmr8balobaj8n7d FOREIGN KEY (user_id) REFERENCES public.t_users(id);


--
-- Name: site_diving_experience_moment fknicl4842x18i3um13wirvlk4e; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_diving_experience_moment
    ADD CONSTRAINT fknicl4842x18i3um13wirvlk4e FOREIGN KEY (moment_id) REFERENCES public.tide_moment(id);


--
-- Name: t_diver_qualification fkojwft3ytalq6ef820rse1miyc; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.t_diver_qualification
    ADD CONSTRAINT fkojwft3ytalq6ef820rse1miyc FOREIGN KEY (qualificationid) REFERENCES public.t_qualification(qualificationid);


--
-- Name: site_diving_experimentation fkqa6jijmpeck06gcbusi0vousj; Type: FK CONSTRAINT; Schema: public; Owner: diving_db_user
--

ALTER TABLE ONLY public.site_diving_experimentation
    ADD CONSTRAINT fkqa6jijmpeck06gcbusi0vousj FOREIGN KEY (site_id) REFERENCES public.site(id);


--
-- PostgreSQL database dump complete
--

\unrestrict gYPoJvAMGUkWfZr4oZpLBVmmbDK9dc9fS2ue8AfLrQiHC3z5DHMFdpCfQhxnrg2

